---
all:
  children:
    windows:
      children:
        rootca:
          hosts:
            ROOTCA:
              ansible_host: 10.10.10.10
        dc:
          hosts:
            DC01:
              ansible_host: 10.10.10.5
        domain_members:
          children:
            subca:
              hosts:
                SUBCA:
                  ansible_host: 10.10.10.20
            client:
              hosts:
                CLIENT:
                  ansible_host: 10.10.10.30
                  vm_template: "{{ vm_template_client }}"
